#index:
#    path: /
#    controller: App\Controller\DefaultController::index

Comentario:
  path: /
  controller: App\Controller\ComentarioController::index

Comentario_user:
  path: /comentariouser
  controller: App\Controller\ComentarioController::indexuser

ComentarioPagina:
  path: /comentariopagina/{copagina}
  controller: App\Controller\ComentarioController::indexpagina


Comentario_detail:
  path: /comentario/{coid}
  controller: App\Controller\ComentarioController::detail

Register:
  path: /registro
  controller: App\Controller\UsuarioController::register

Login:
  path: /login
  controller: App\Controller\UsuarioController::login

Logout:
  path: /logout