#index:
#    path: /
#    controller: App\Controller\DefaultController::index

Comentario:
  path: /
  controller: App\Controller\ComentarioController::index

Register:
  path: /registro
  controller: App\Controller\UsuarioController::register

Login:
  path: /login
  controller: App\Controller\UsuarioController::login

Logout:
  path: /logout